### ISSUE TITLE
Management API: change log level on the fly

### ISSUE THREAD

**Issue by folex** [fluencelabs/nox#1062]
Ability to change node's log level and log filters without restarting the node. That would simplify debug process by node operators while keeping the network more stable. 

## Technical details
- `RUST_LOG` env variable currently manages log level from the outside
- `env_logger` is used to control logging
- `WASM_LOG` env variable controls log level of the underlying Wasm Runtime (FCE)

## Things to consider
- `tracing` library may provide more convenient API for the task while also enabling more structured logging. Worth looking into, but not necessary. 
- Most likely, to change FCE log level one would need to add special API to FCE as it is most likely isn't possible to change `WASM_LOG` without recreating FCE

**Comment by meph** [comment]
I'm going to close this issue for now, but if you believe it warrants further discussion or if it becomes relevant in the future, please feel free to reopen it.
