### ISSUE TITLE
Script Storage: persist scripts

### ISSUE THREAD

**Issue by folex** [fluencelabs/nox#1063]
Script storage provides functionality of recurring scripts. One can upload a script there, specify an interval, and script will be executed once in the interval until deleted. 

However, scripts are stored only in node's memory. So if node is restarted, all scripts are lost. To fix that, scripts must be stored on disk, and retrieved on each restart.

## Things to consider
- All services are persisted on disk and recreated after restart. One can follow similar mechanics with script storage persistence. See `PersistedService` for implementation.

**Comment by folex** [comment]
This issue just became a tad more complex because of #1118. 

Now we have builtin services automatically deployed and these services have associated scheduled scripts. These scheduled scripts are added anew on each node restart. 

Thus simply persisting scripts is not enough: persistence should also provide a way to deduplicate scripts.

**Comment by meph** [comment]
I'm going to close this issue for now, but if you believe it warrants further discussion or if it becomes relevant in the future, please feel free to reopen it.
