### ISSUE TITLE
Service garbage collection

### ISSUE THREAD

**Issue by folex** [fluencelabs/nox#1066]
## The problem
Currently, services are created and retained forever. That bloats nodes on the network and eats resources (mostly memory). 

While it is possible to remove services manually (also, see #1065), it is currently impossible to tell whether service is used or not. In other words, deleting a service could break someone's app, and we don't want that.

So we need a way to tell which services are used or relied upon, and which ones are safe to remove to free up resources.

## Approach
I see 2 possible approaches here:

### 1. Separate `GarbageCollector` service
Separate service that holds a list (directory) of all recently used services. If a developer or author wants her service to be retained, she must check-in within the `GarbageCollectior` service by calling a function `check_in` (or similar). That would mark her service active, so it won't be deleted. 

If a service isn't marked active for some time, it is deleted from the list. Node hosters are free to use the `GarbageCollector` service to know which services are safe to be deleted, and which ones are used and should be preserved. However easy, deletion should be executed manually.

### 2. Built-in mechanics
Node tracks all services, so it is rather easy to keep a timestamp of last function call on the service. Different policies could be implemented on top of this information - automatic or manual.

## Things to consider
- Should `auto_*` particles make services active? If yes, this created a loophole where a script can keep a service active forever even though there are no users.

**Comment by meph** [comment]
I'm going to close this issue for now, but if you believe it warrants further discussion or if it becomes relevant in the future, please feel free to reopen it.
