### ISSUE TITLE
cli parameter to override  metrics port

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/nox#1108]
so can pass https://github.com/fluencelabs/fluence/blob/714fe6a6d2dcb1779491ad4372c61f9cc2f3d13b/deploy/Config.default.toml#L38 from shell easy

**Comment by meph** [comment]
I'm going to close this issue for now, but if you believe it warrants further discussion or if it becomes relevant in the future, please feel free to reopen it.
