### ISSUE TITLE
srv add_alias should fail if alias already exists

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/nox#1131]
current behavior - several services under same alias on one node

**Comment by folex** [comment]
Can you elaborate on how to reproduce this bug? Or how to observe it?

**Comment by folex** [comment]
It shouldn't be possible to have 2 services under the same alias. When you do `add_alias`, it removes alias from the previously aliased service

**Comment by dzmitry-lahoda** [comment]
i saw it. there is bug. 4 services under same alias. via srv call to show services.

**Comment by dzmitry-lahoda** [comment]
so it not removed for some reason.

**Comment by folex** [comment]
Yeah, I see you mean `srv list`. There was a bug in the persistence, it's fixed in #1129. 

However, there was always a single service_id corresponding to an alias.
