### ISSUE TITLE
remove dashes from ids (cb582829-c07f-475c-913c-f3794c754ff3 -> cb582829c07f475c913cf3794c754ff3)

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/nox#1133]
more space, harder to copy. may be encode in more symbols (a-z)

**Comment by folex** [comment]
It's the UUID v4 format

**Comment by dzmitry-lahoda** [comment]
uuid has semantics (how it generated), uuid has some kind of limit (128 bit number) and it has representation. 
there are uuids which put timestamep into first bits (impls are on rust, js, etc) - same 128 bits, but better ordered, mostly same randomness. and what is more wide spread - make uids shorter to and double click selectable - to change only form to `asdjqkPweAhjA213w2z`. So can renatin semantics, but better format, or change semantics too https://github.com/ulid/spec

**Comment by dzmitry-lahoda** [comment]
01FACS45HN8P8H4CZGW0M1N0A0

**Comment by dzmitry-lahoda** [comment]
can double click to copy

**Comment by dzmitry-lahoda** [comment]
and users will create service per something -> very good
