### ISSUE TITLE
Unknown behaviour Srv.add_alias on fail to add alias

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/nox#1158]
```
service Srv("srv"):
    add_alias(alias: string, service_id: string)
```

would it throw exception or return some error code? could that build in return some error code like structure?

**Comment by folex** [comment]
It would throw an error that you can catch with `try`

**Comment by dzmitry-lahoda** [comment]
how can i throw error from rust code of mt service? just if that is possible. what would be error code to check if alias is wrong or i have not enough rights?

**Comment by folex** [comment]
> how can i throw error from rust code of mt service?
Currently, there's no way to do that. Errors from protocol services are meant to be caught via `xor`/`try`, and business logic errors are meant to be handled via `if result.success: ... else: ...`

> what would be error code to check if alias is wrong or i have not enough rights
if `add_alias` failed, then why do you want to distinguish specific error? For what use case?

**Comment by dzmitry-lahoda** [comment]
> Currently, there's no way to do that. 

May be i can panic in Rust in marine method and get exceptions?

> Errors from protocol services are meant to be caught via xor/try, and business logic errors are meant to be handled via if result.success: ... else: ...

If I have not enough rights to create alias, is not that business logic? `You do not have rights to create alias`, 401 or 403.  

> if add_alias failed, then why do you want to distinguish specific error? For what use case?

If error is structured (has some field to == with), I can ask use to check if he ads alias to node he manages as well formed text. I am not sure what current text is, but if not to handle try/catch it seems was some hang or like.

**Comment by dzmitry-lahoda** [comment]
>  add_alias(alias: string, service_id: string)
