### ISSUE TITLE
Builtins: add Script.upload that loads scripts from particle vault

### ISSUE THREAD

**Issue by folex** [fluencelabs/nox#1191]
It's in the name. If you have an AIR script in IPFS, it's not easy to add it via `Script.add` (see #1190). 

It's possible to improve situation with a simple method:
```
service Script("script"):
  upload(path: string, interval: ?u64)
```
It should read file from particle file vault and then work exactly the same as `Script.add`

**Comment by alari** [comment]
Maybe call it `Script.add_file`? As no uploading happens indeed.
