### ISSUE TITLE
Add builtins for Metrics

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/nox#1199]
so i can track service metrics
like it happens in k8s when each metrics is tagged by docker pod etc

**Comment by dzmitry-lahoda** [comment]
nope, ceramic does not suits. need realtime compressed cheap histograms built in

**Comment by dzmitry-lahoda** [comment]
than info can be used for routing, circuit breakers, pricing.

**Comment by dzmitry-lahoda** [comment]
> How would that make it more secure?

DHT like security seems suits. But anyway - any kind of stats are needed. I doubt app devs should build these. And Prometheus seems rather nice for starter. Metrics != Analytics. Metrics are more realtime = Fine to restart noes and lost info.

**Comment by folex** [comment]
> I want to store metrics which are custom, like failed deliveries.

Makes sense, so you basically want an integration with time-series database like Prometheus or TimescaleDB. To me that sounds like a service one could deploy to its own nodes rather than a network-wide built-in.

**Comment by dzmitry-lahoda** [comment]
> There's no way to have a metric that would tell if a user is online or offline. It can only be done with some keep-alive mechanic.

There is:)
