### ISSUE TITLE
Feature request: ability to restrict who can deploy services to nodes

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/nox#1208]
so default is black listed all

**Comment by folex** [comment]
We have plans for that feature, but it's not on the shortlist.

So right now, the easiest way is to modify the code. We already have some builtins restricted only to the admin (management) key, see for example [add_alias](https://github.com/fluencelabs/fluence/blob/411408fbccaaca6df22c98ba926bde6d5c0bb89d/particle-services/src/app_services.rs#L224-L238).

It's possible to introduce this logic for `srv deploy` as well.
