### ISSUE TITLE
Scheduled scripts: add origin

### ISSUE THREAD

**Issue by folex** [fluencelabs/nox#1215]
Right now, it's impossible to respect authorization for particles triggered by scheduled scripts.

To address this issue, it should be possible to discern two things about a particle issued by a scheduled script:
1. What user has created this script. This would allow to apply auth restrictions to function calls.
2. If this particle is caused by a scheduled script or by a normal user-executed script.

**Comment by swarna1101** [comment]
One way to associate a scheduled script with a specific user or service account is to use an authentication mechanism, such as OAuth, to identify the user or service account when the script is created. The script could then be stored in a database or other persistent storage system with a reference to the user or service account that created it. When the scheduled script is triggered, the system could look up the user or service account associated with the script and check their permissions before executing the script.

It may also be useful to distinguish between particles triggered by scheduled scripts and those triggered by normal user-executed scripts. This could be done by storing additional metadata with the script, such as a flag indicating whether it is a scheduled script or a user-executed script. This information could then be used to apply different authorization rules or take different actions based on the type of script being executed.

```rust
// Check if the user or service account associated with the script has the necessary permissions to execute it.
fn check_auth(script: &Script) -> Result<(), AuthError> {
    let user = script.user;
    let required_permission = script.required_permission;

    // Look up the user in the database and check their permissions.
    let user_record = User::find(user.id)?;
    if !user_record.has_permission(required_permission) {
        return Err(AuthError::InsufficientPermissions);
    }

    Ok(())
}

// Execute the particle.
fn execute_particle(particle: &Particle) -> Result<(), ExecutionError> {
    // Check if the particle was triggered by a scheduled script.
    if let Some(script) = particle.script {
        // Check authorization for the script.
        check_auth(script)?;
    }

    // Perform the particle's actions.
    // ...

    Ok(())
}
```

This example assumes that there is a Script struct that stores information about a scheduled script, including the user or service account that created it and the required permission for executing it. It also assumes the existence of a User struct that represents a user or service account in the database and has a method has_permission for checking whether the user has a particular permission.

The check_auth function takes a reference to a Script and checks if the user or service account associated with the script has the necessary permissions to execute it. If the user does not have the required permission, it returns an error indicating that insufficient permissions were granted.

The execute_particle function takes a reference to a Particle and first checks if the particle was triggered by a scheduled script. If it was, it calls the check_auth function to ensure that the user or service account associated with the script has the necessary permissions. If the authorization check passes, the function can proceed to perform the particle's actions.

**Comment by meph** [comment]
Scheduled script functionality was replaced by Spells. 

I'm going to close this issue for now, but if you believe it warrants further discussion or if it becomes relevant in the future, please feel free to reopen it.
