### ISSUE TITLE
Move from CIrcleCI to GitHub Actions

### ISSUE THREAD

**Issue by folex** [fluencelabs/nox#1265]
As CircleCI showed to be unreliable and stopped worked entirely, we have to migrate `Publish Branch` to GitHub Actions. It's better to use `self-hosted` for that purpose.

**Comment by swarna1101** [comment]
If you are experiencing reliability issues with CircleCI and need to migrate your publish branch to GitHub Actions, there are a few steps you can follow to set up GitHub Actions for your project:

1. Set up a new repository on GitHub for your project, if you haven't already.
2. Install the GitHub Actions app on your repository by going to the Settings page for your repository and clicking on the "Actions" tab.
3. Create a new workflow file in your repository by going to the Actions tab and clicking on the "Set up a workflow yourself" button.
4. Edit the workflow file to specify the tasks you want to automate and the events that should trigger the workflow. You can use the YAML syntax to specify the tasks and events in the workflow file.
5. Commit and push the workflow file to your repository to activate the workflow.

Once you have set up your workflow, GitHub Actions will automatically run the tasks you have specified whenever the specified events occur. You can use GitHub Actions to automate a wide range of tasks, including building, testing, and deploying your code.

Keep in mind that there are many ways to set up and configure GitHub Actions for your project, and the specific steps you need to follow will depend on your specific needs and use case. You may need to modify the steps I have provided to meet the requirements of your project.
