### ISSUE TITLE
P2P file sharing demo app is not free software

### ISSUE THREAD

**Issue by ian-kelling** [fluencelabs/nox#967]
Repro:

I go to https://relay01.fluence.dev/

It tells me: "You need to enable JavaScript to run this app." So, I open the page source to see if the javascript is free (that means, I have the source code and a free software license to use it). I see no license, and some minified javascript (minified js is not source code). Perhaps the source code and license exists somewhere on the internet, but since I don't know it, it's not free for me. 

For one way to communicate that information, see https://www.gnu.org/philosophy/javascript-trap.html .

**Comment by folex** [comment]
Hello! Thank you for reaching out. 

That's a great idea to include a license (or a link to it) to webpage source code, we'll definitely look into that. Thank you! 🙂 

I'll leave the issue open until we implement this as a practice for out web apps, or move forward in any other way.

**Comment by swarna1101** [comment]
It is important for developers to properly license their software and make it clear to users how the software can be used. When you visit a website and see a message telling you that you need to enable JavaScript to use the site, it means that the website is using JavaScript code to run certain features or functionality.

If you want to use the JavaScript code on the website, it is important to make sure that you have the necessary rights to do so. This usually involves checking the license of the software and ensuring that you have permission to use it in your specific context. In some cases, the website may include information about the license in the source code or elsewhere on the site. In other cases, you may need to contact the website or software developer to inquire about the license and obtain permission to use the code.

If you are unable to find information about the license or obtain permission to use the code, it is important to respect the rights of the software developer and not use the code without permission. This is especially important if you are building a commercial application or using the code in a way that could be considered a derivative work.
